## Agenda for Day 6: (session 7)
- Date: 17/02/2020 Evening 6:30 -  10:00

---
- workshop solution (quick implementation - 10 mins)

---

- Data Analysis Foundations
    - using numpy (5%)
    - using pandas (95%)

---

- Data Visualization Foundations
    - using matplotlib
    - using seaborn
    - using plot.ly
---

### Tools / Libraries
- numpy, pandas

- matplotlib, seaborn, plot.py

## numpy = array(ndim) intro

In [8]:
x[0]

10

In [9]:
x[-1]

30

In [10]:
x[:2]

[10, 20]

In [4]:
x= [10,20,30]

In [18]:
x2 = [
    [1,2,1],
    [0,1,0]
]

In [13]:
x2[0][1:]

[2, 1]

In [19]:
x3 = [
    [
        [1,2],
        [2,2]
    ],
    [
        [0,0],
        [0,1]
    ],
    [
        [4,1],
        [4,1]
    ]
    
]

In [21]:
import numpy as np

In [45]:
%%time
items = list(range(100000000))

Wall time: 2.3 s


In [43]:
%%time
curr_max = 0
for i in items:
    if i > curr_max:
        curr_max = i
curr_max

Wall time: 10.8 s


99999999

In [44]:
%%time
items_array = np.array(items)

Wall time: 5.63 s


In [48]:
%%time
items_array = np.arange(100000000)

Wall time: 204 ms


In [47]:
%%time
items_array.max(),items_array.min(), items_array.argmax(), items_array.mean(), items_array.std(), items_array.var()

Wall time: 2.54 s


(99999999, 0, 99999999, 49999999.5, 28867513.459478058, 833333333333146.9)

In [26]:
#min element
curr_min = 0
for i in items:
    if i < curr_min:
        curr_min = i
curr_min

0

In [61]:
## Create some array


[[1, 1], [2, 2], [3, 3]]

In [51]:
x = [10,20.,30]
X = np.array(x)
X

array([10., 20., 30.])

In [55]:
x = [10,'20',30]
X = np.array(x, dtype=np.float64)
X

array([10., 20., 30.])

In [56]:
#create a numpy array of (4 rows,5 columns)

# .....
# .....
# .....
# .....

shape = (4,5)
np.ones()
np.zeros()
np.full(?,?)
np.random.randint

<module 'numpy' from 'C:\\Users\\balap\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [57]:
np.ones(shape)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.zeros(shape, dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [60]:
np.full(shape, 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [65]:
np.random.random(shape)

array([[0.21476104, 0.51492305, 0.04147036, 0.9584169 , 0.84289202],
       [0.83755244, 0.58234545, 0.84338911, 0.7954705 , 0.22090732],
       [0.95855778, 0.28852464, 0.62367005, 0.24492643, 0.82867565],
       [0.59742925, 0.98222739, 0.23954887, 0.1020702 , 0.15423742]])

In [66]:
X = np.array([
    [1,1],
    [2,2],
    [3,3]
])

In [70]:
X.shape

(3, 2)

In [71]:
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
## index things in a array
## slice items , rows/columns

# X[ row_index , col_index ]

# X[         ? ,    ? ]


In [103]:
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [79]:
X[0 ,  ]

array([1, 1])

In [80]:
X[0:1, : ]

array([[1, 1]])

In [ ]:
X[ 1:, :]

df.iloc[:5, 1:3]

In [78]:
X [1:2,  0:1]

array([[2]])

In [ ]:
X[0,0]
X[0:1,0:1]

X[[0,1], [1,1]]

In [106]:
X[[0,0,1,1], : ]

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [108]:
X[[1,0], :]

array([[2, 2],
       [1, 1]])

In [110]:
X[:, [1,0,1,0,1,1,1]]

array([[1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3]])

In [111]:
X[ [0,1], [0,1]] #useless 

array([1, 2])

In [91]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head(7)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2

In [98]:
df.iloc[100,3]

'Yes'

In [99]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [100]:
df.iloc[-1,3]

'No'

In [101]:
df.iloc[-5:, : ]

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [102]:
df.iloc[-5:, ::-1 ]

size    time   day smoker     sex   tip  total_bill
239     3  Dinner   Sat     No    Male  5.92       29.03
240     2  Dinner   Sat    Yes  Female  2.00       27.18
241     2  Dinner   Sat    Yes    Male  2.00       22.67
242     2  Dinner   Sat     No    Male  1.75       17.82
243     2  Dinner  Thur     No  Female  3.00       18.78

In [113]:
df.iloc[-5:,   [0,-1, 4]]

total_bill  size   day
239       29.03     3   Sat
240       27.18     2   Sat
241       22.67     2   Sat
242       17.82     2   Sat
243       18.78     2  Thur

In [114]:
df.iloc[[0,1],  [0,-1, 4]]

total_bill  size  day
0       16.99     2  Sun
1       10.34     3  Sun

In [ ]:
## Example with df (Pandas)

In [90]:
df.iloc[ :5, -1]

0    2
1    3
2    3
3    2
4    4
Name: size, dtype: int64

In [97]:
df.iloc[ :5, -1:-3:1]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [96]:
df.iloc[ :5, -1:-3:-1]

size    time
0     2  Dinner
1     3  Dinner
2     3  Dinner
3     2  Dinner
4     4  Dinner

In [92]:
df.iloc[ :5, -1:]

size
0     2
1     3
2     3
3     2
4     4

In [95]:
df.iloc[ :2, -1]

0    2
1    3
Name: size, dtype: int64

In [94]:
df.iloc[ :2, -1:]

size
0     2
1     3

In [84]:
df.iloc[ :5, 1:3]

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female

In [116]:
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [117]:
a = [10,20,3]
# a + 2
a * 2 #
# a / 2
# a < 2
# a > 2

[10, 20, 3, 10, 20, 3]

In [118]:
a = [10,20,3]
a + 2
# a * 2 #
a / 2
a < 2
a > 2

TypeError: can only concatenate list (not "int") to list

In [120]:
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [123]:
## mask | operations
X > 1

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [125]:
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [130]:
# mask = df.time == "Dinner"
# df[mask]

In [131]:
# 40records female
# 60records male
# filter only male records
mask = df.sex == "Male"
df[mask]

total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [132]:
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [133]:
mask1 = X > 2
mask1

array([[False, False],
       [False, False],
       [ True,  True]])

In [134]:
mask2 = X < 6
mask2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [136]:
mask = mask1 & mask2
mask

array([[False, False],
       [False, False],
       [ True,  True]])

In [137]:
#print all the values above > 1
mask1 = X > 2
mask2 = X < 6
mask = mask1 & mask2
X[ mask ]

array([3, 3])

In [141]:
# X[  (X>2) & (X<6) ]

In [ ]:
X * 2

In [ ]:
X / 2

In [ ]:
X % 2

In [ ]:
# logical | comparison opeators
X == 0
X > 1
X < 1
X == "hello"

In [143]:
X == 0

X[X == 0]

array([], dtype=int32)

In [ ]:
X[mask]

In [144]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [153]:
## filter all the records, where smoker = No
# df.iloc[?, ?]
mask = df.iloc[:, 3] == "No"
df[mask]

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 7 columns]

In [151]:
## filter all the records, where smoker = No
mask = df.smoker == "No"
df[mask]

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 7 columns]

In [166]:
df.head()


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head(7)
df.shape[0]
len(df)

In [171]:
# count total no of female records
mask = df.sex == "Female"
res = df[mask]
len(res)

87

In [176]:
final_mask

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241     True
242    False
243    False
Length: 244, dtype: bool

In [181]:
# df.loc[ final_mask , ['tip'] ]
# del df['is_true_or_false']

In [184]:
# count total no of male smokers
#df.sex = "Male"
mask1 = df.sex == "Male"
mask2 = df.smoker == "Yes"
final_mask = mask1 & mask2

#df.loc[final_mask, ["total_bill","tip"]]

res = df[final_mask]
df2 = res.loc[ : , ['total_bill' , 'tip'] ]

In [193]:
# find out maximum total_bill given by someone on (Sunday) (dinner) time

m1 = df.day == "Sun"
m2 = df.time == "Dinner"
mask = m1 & m2
res = df.loc[mask, "total_bill"]
res.max()

48.17

In [198]:
res.sort_values(ascending=False).iloc[0]

48.17

In [202]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [207]:
# average tips for :(male)
df.loc[(df.sex == "Male"), "tip"].mean()

mask = df.sex == "Male"
res  = df.loc[mask, "tip"]
res.mean()

3.0896178343949052

In [208]:
df.loc[(df.sex == "Male") & (df.time == "Dinner"), "tip"].mean()

3.1448387096774195

In [209]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [152]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [154]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [159]:
## select time and size columns

# df.iloc[:, -2:]
# df.iloc[:, [-2,-1]]
df.iloc[:, [5,6]]

df.loc[ 0:3 , "time" ]
df.loc[ 0:3 , ["time","size"] ]
df.loc[ 0:3 , "tip":"day"] #sepecial - ending index inclusive..

time  size
0    Dinner     2
1    Dinner     3
2    Dinner     3
3    Dinner     2
4    Dinner     4
..      ...   ...
239  Dinner     3
240  Dinner     2
241  Dinner     2
242  Dinner     2
243  Dinner     2

[244 rows x 2 columns]

In [160]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [161]:
df.index #row inde

RangeIndex(start=0, stop=244, step=1)

In [162]:
df.columns #column index

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [164]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [165]:
df.loc[10:15, ["tip","total_bill"] ]

tip  total_bill
10  1.71       10.27
11  5.00       35.26
12  1.57       15.42
13  3.00       18.43
14  3.02       14.83
15  3.92       21.58

## Series Vs DataFrame

In [212]:
sns.load_dataset??

In [ ]:
https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv